# Generated by Django 5.1.7 on 2025-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='hehehe', max_length=100),
            preserve_default=False,
        ),
    ]
