# Generated by Django 5.1.7 on 2025-04-08 12:56

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cartorder_oid_cartorder_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="oid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                blank=True,
                length=5,
                max_length=20,
                null=True,
                prefix="oid",
            ),
        ),
    ]
