# Generated by Django 5.1.7 on 2025-04-08 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_cartorder_oid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
