# Generated by Django 5.1.7 on 2025-06-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orders_count', models.IntegerField(default=0)),
                ('products_count', models.IntegerField(default=0)),
                ('monthly_earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Dashboard Analytics',
                'verbose_name_plural': 'Dashboard Analytics',
            },
        ),
    ]
